// flow-typed signature: d4a4d0a36d581ec3b46eb210e48a80fd
// flow-typed version: <<STUB>>/eslint-plugin-react-native-a11y_v1.2.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-native-a11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-native-a11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-react-native-a11y/__tests__/__util__/parserOptionsMapper' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/__tests__/__util__/ruleOptionsMapperFactory' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/accessibility-label-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-accessibility-props-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-component-type-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-live-region-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-role-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-states-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-traits-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-important-for-accessibility-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/no-nested-touchables-test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/factory/valid-prop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/rules/accessibility-label' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/rules/has-accessibility-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-component-type' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-live-region' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-role' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-state' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-states' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-traits' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-important-for-accessibility' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/rules/no-nested-touchables' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/util/findChild' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/util/isOneOf' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/util/isTouchable' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/lib/util/schemas' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/scripts/addRuleToIndex' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/scripts/boilerplate/doc' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/scripts/boilerplate/rule' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/scripts/boilerplate/test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-native-a11y/scripts/create-rule' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-react-native-a11y/__tests__/__util__/parserOptionsMapper.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/__util__/parserOptionsMapper'>;
}
declare module 'eslint-plugin-react-native-a11y/__tests__/__util__/ruleOptionsMapperFactory.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/__util__/ruleOptionsMapperFactory'>;
}
declare module 'eslint-plugin-react-native-a11y/__tests__/index-test.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/index-test'>;
}
declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/accessibility-label-test.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/src/rules/accessibility-label-test'>;
}
declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-accessibility-props-test.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/src/rules/has-accessibility-props-test'>;
}
declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-component-type-test.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-component-type-test'>;
}
declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-live-region-test.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-live-region-test'>;
}
declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-role-test.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-role-test'>;
}
declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-states-test.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-states-test'>;
}
declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-traits-test.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-accessibility-traits-test'>;
}
declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-important-for-accessibility-test.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/src/rules/has-valid-important-for-accessibility-test'>;
}
declare module 'eslint-plugin-react-native-a11y/__tests__/src/rules/no-nested-touchables-test.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/__tests__/src/rules/no-nested-touchables-test'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/factory/valid-prop.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/factory/valid-prop'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/index'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/rules/accessibility-label.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/rules/accessibility-label'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/rules/has-accessibility-props.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/rules/has-accessibility-props'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-component-type.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-component-type'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-live-region.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-live-region'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-role.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-role'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-state.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-state'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-states.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-states'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-traits.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/rules/has-valid-accessibility-traits'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/rules/has-valid-important-for-accessibility.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/rules/has-valid-important-for-accessibility'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/rules/no-nested-touchables.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/rules/no-nested-touchables'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/util/findChild.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/util/findChild'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/util/isOneOf.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/util/isOneOf'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/util/isTouchable.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/util/isTouchable'>;
}
declare module 'eslint-plugin-react-native-a11y/lib/util/schemas.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/lib/util/schemas'>;
}
declare module 'eslint-plugin-react-native-a11y/scripts/addRuleToIndex.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/scripts/addRuleToIndex'>;
}
declare module 'eslint-plugin-react-native-a11y/scripts/boilerplate/doc.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/scripts/boilerplate/doc'>;
}
declare module 'eslint-plugin-react-native-a11y/scripts/boilerplate/rule.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/scripts/boilerplate/rule'>;
}
declare module 'eslint-plugin-react-native-a11y/scripts/boilerplate/test.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/scripts/boilerplate/test'>;
}
declare module 'eslint-plugin-react-native-a11y/scripts/create-rule.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-a11y/scripts/create-rule'>;
}
